import React from 'react'

import NftDashboardPage from '@app/pages/DashboardPages/NftDashboardPage'
import MedicalDashboardPage from '@app/pages/DashboardPages/MedicalDashboardPage'
import {withLoading} from '@app/hocs/withLoading.hoc'

const AuthLayout = React.lazy(() => import('@app/components/layouts/AuthLayout/AuthLayout'))
const NewsFeedPage = React.lazy(() => import('@app/pages/NewsFeedPage'))
const KanbanPage = React.lazy(() => import('@app/pages/KanbanPage'))
const DataTablesPage = React.lazy(() => import('@app/pages/DataTablesPage'))
const ChartsPage = React.lazy(() => import('@app/pages/ChartsPage'))
const ServerErrorPage = React.lazy(() => import('@app/pages/ServerErrorPage'))
const Error404Page = React.lazy(() => import('@app/pages/Error404Page'))
const AdvancedFormsPage = React.lazy(() => import('@app/pages/AdvancedFormsPage'))
const PersonalInfoPage = React.lazy(() => import('@app/pages/PersonalInfoPage'))
const SecuritySettingsPage = React.lazy(() => import('@app/pages/SecuritySettingsPage'))
const NotificationsPage = React.lazy(() => import('@app/pages/NotificationsPage'))
const PaymentsPage = React.lazy(() => import('@app/pages/PaymentsPage'))
const ButtonsPage = React.lazy(() => import('@app/pages/uiComponentsPages/ButtonsPage'))
const SpinnersPage = React.lazy(() => import('@app/pages/uiComponentsPages/SpinnersPage'))
const AvatarsPage = React.lazy(() => import('@app/pages/uiComponentsPages/dataDisplay/AvatarsPage'))
const BadgesPage = React.lazy(() => import('@app/pages/uiComponentsPages/dataDisplay/BadgesPage'))
const CollapsePage = React.lazy(() => import('@app/pages/uiComponentsPages/dataDisplay/CollapsePage'))
const PaginationPage = React.lazy(() => import('@app/pages/uiComponentsPages/dataDisplay/PaginationPage'))
const ModalsPage = React.lazy(() => import('@app/pages/uiComponentsPages/modals/ModalsPage'))
const PopoversPage = React.lazy(() => import('@app/pages/uiComponentsPages/modals/PopoversPage'))
const PopconfirmsPage = React.lazy(() => import('@app/pages/uiComponentsPages/modals/PopconfirmsPage'))
const ProgressPage = React.lazy(() => import('@app/pages/uiComponentsPages/feedback/ProgressPage'))
const ResultsPage = React.lazy(() => import('@app/pages/uiComponentsPages/feedback/ResultsPage'))
const AlertsPage = React.lazy(() => import('@app/pages/uiComponentsPages/feedback/AlertsPage'))
const SkeletonsPage = React.lazy(() => import('@app/pages/uiComponentsPages/feedback/SkeletonsPage'))
const InputsPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/InputsPage'))
const CheckboxesPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/CheckboxesPage'))
const RadiosPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/RadiosPage'))
const SelectsPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/SelectsPage'))
const SwitchesPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/SwitchesPage'))
const UploadsPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/UploadsPage'))
const RatesPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/RatesPage'))
const AutoCompletesPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/AutoCompletesPage'))
const StepsPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/StepsPage'))
const DateTimePickersPage = React.lazy(() => import('@app/pages/uiComponentsPages/forms/DateTimePickersPage'))
const DropdownsPage = React.lazy(() => import('@app/pages/uiComponentsPages/DropdownsPage'))
const BreadcrumbsPage = React.lazy(() => import('@app/pages/uiComponentsPages/navigation/BreadcrumbsPage'))
const TabsPage = React.lazy(() => import('@app/pages/uiComponentsPages/navigation/TabsPage'))
const NotificationsUIPage = React.lazy(() => import('@app/pages/uiComponentsPages/feedback/NotificationsPage'))
const GoogleMaps = React.lazy(() => import('@app/pages/maps/GoogleMapsPage/GoogleMapsPage'))
const LeafletMaps = React.lazy(() => import('@app/pages/maps/LeafletMapsPage/LeafletMapsPage'))
const ReactSimpleMaps = React.lazy(() => import('@app/pages/maps/ReactSimpleMapsPage/ReactSimpleMapsPage'))
const PigeonsMaps = React.lazy(() => import('@app/pages/maps/PigeonsMapsPage/PigeonsMapsPage'))
const Logout = React.lazy(() => import('./Logout'))

// const LoginPageWL = withLoading(LoginPage);
export const MedicalDashboard = withLoading(MedicalDashboardPage)
export const NftDashboard = withLoading(NftDashboardPage)
export const NewsFeed = withLoading(NewsFeedPage)

// const NewsFeed = NewsFeedPage;
export const Kanban = withLoading(KanbanPage)
export const AdvancedForm = withLoading(AdvancedFormsPage)

// UI Components
export const Buttons = withLoading(ButtonsPage)
export const Spinners = withLoading(SpinnersPage)
export const Inputs = withLoading(InputsPage)
export const Checkboxes = withLoading(CheckboxesPage)
export const Radios = withLoading(RadiosPage)
export const Selects = withLoading(SelectsPage)
export const Switches = withLoading(SwitchesPage)
export const Uploads = withLoading(UploadsPage)
export const Rates = withLoading(RatesPage)
export const AutoCompletes = withLoading(AutoCompletesPage)
export const Steps = withLoading(StepsPage)
export const DateTimePickers = withLoading(DateTimePickersPage)
export const Dropdowns = withLoading(DropdownsPage)
export const Breadcrumbs = withLoading(BreadcrumbsPage)
export const Tabs = withLoading(TabsPage)
export const Avatars = withLoading(AvatarsPage)
export const Badges = withLoading(BadgesPage)
export const Collapse = withLoading(CollapsePage)
export const Pagination = withLoading(PaginationPage)
export const Modals = withLoading(ModalsPage)
export const Popovers = withLoading(PopoversPage)
export const Popconfirms = withLoading(PopconfirmsPage)
export const Progress = withLoading(ProgressPage)
export const Results = withLoading(ResultsPage)
export const Alerts = withLoading(AlertsPage)
export const NotificationsUI = withLoading(NotificationsUIPage)
export const Skeletons = withLoading(SkeletonsPage)

export const DataTables = withLoading(DataTablesPage)
export const Charts = withLoading(ChartsPage)

// Maps
export const Google = withLoading(GoogleMaps)
export const Leaflet = withLoading(LeafletMaps)
export const ReactSimple = withLoading(ReactSimpleMaps)
export const Pigeons = withLoading(PigeonsMaps)

export const ServerError = withLoading(ServerErrorPage)
export const Error404 = withLoading(Error404Page)

// Profile
export const PersonalInfo = withLoading(PersonalInfoPage)
export const SecuritySettings = withLoading(SecuritySettingsPage)
export const Notifications = withLoading(NotificationsPage)
export const Payments = withLoading(PaymentsPage)

export const AuthLayoutFallback = withLoading(AuthLayout)
export const LogoutFallback = withLoading(Logout)
